// packages/devextreme-cli/src/templates/react/application/src/components/user-panel/UserPanel.tsx
import React, { useRef, useCallback } from 'react';
import DropDownButton from 'devextreme-react/drop-down-button';
import { Template } from 'devextreme-react/core/template';
import { useAuth } from '../../contexts/auth';
import './UserPanel.scss';
<%=#isTypeScript%>import type { UserPanelProps } from '../../types';<%=/isTypeScript%>
import { UserMenuSection } from '../user-menu-section/UserMenuSection';

export default function UserPanel({ menuMode }<%=#isTypeScript%>: UserPanelProps<%=/isTypeScript%>) {
  const { user } = useAuth();

  const dropDownButtonAttributes = {
    class: 'user-button'
  };

  const buttonDropDownOptions = {
    width: 'auto'
  };

  const dropDownBtn = useRef<%=#isTypeScript%><DropDownButton><%=/isTypeScript%>(null);
  const onMenuItemClick = useCallback(() => {
    dropDownBtn.current<%=#isTypeScript%>?<%=/isTypeScript%>.instance.close();
  }, []);

  return (
    <div className={'user-panel'}>
      {menuMode === 'context' && (
        <DropDownButton stylingMode='text'
          ref={dropDownBtn}
          icon={user<%=#isTypeScript%>?<%=/isTypeScript%>.avatarUrl} 
          showArrowIcon={false}
          elementAttr={dropDownButtonAttributes}
          dropDownOptions={buttonDropDownOptions}
          dropDownContentTemplate='dropDownTemplate'
        >
          <Template name='dropDownTemplate'>
            <UserMenuSection onMenuItemClick={onMenuItemClick} />
          </Template>
        </DropDownButton>
      )}
      {menuMode === 'list' && (
        <UserMenuSection
          showAvatar
          className={'dx-toolbar-menu-action'}
        />
      )}
    </div>
  );
}

// packages/devextreme-schematics/src/add-layout/files/src/app/shared/components/user-panel/user-panel.component.ts
import { Component, NgModule, Input, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';

import { DxDropDownButtonModule, DxDropDownButtonComponent } from 'devextreme-angular/ui/drop-down-button';
import { UserMenuSectionModule } from '../user-menu-section/user-menu-section.component';
import { IUser } from '../../services/auth.service';

@Component({
  selector: 'app-user-panel',
  templateUrl: 'user-panel.component.html',
  styleUrls: ['./user-panel.component.scss']
})

export class UserPanelComponent {
  @Input()
  menuItems: any;

  @Input()
  menuMode!: string;

  @Input()
  user!: IUser | null;

  @ViewChild(DxDropDownButtonComponent) dropDownBtn?: DxDropDownButtonComponent;

  onMenuItemClick() {
    this.dropDownBtn?.instance.close();
  }

  constructor() {}
}

@NgModule({
  imports: [
    DxDropDownButtonModule,
    UserMenuSectionModule,
    CommonModule,
  ],
  declarations: [ UserPanelComponent ],
  exports: [ UserPanelComponent ]
})
export class UserPanelModule { }

<div class="user-panel">
  <dx-drop-down-button
    *ngIf="menuMode === 'context'"
    stylingMode="text"
    dropDownContentTemplate="dropDownTemplate"
    [icon]="user?.avatarUrl"
    [showArrowIcon]="false"
    [elementAttr]="{
      class: 'user-button'
    }"
    [dropDownOptions]="{
      width: 'auto'
    }"
  >
    <div *dxTemplate="let data of 'dropDownTemplate'">
      <user-menu-section
        [menuItems]="menuItems"
        [showAvatar]="false"
        [user]="user"
        (onMenuItemClick)="onMenuItemClick()"
      />
    </div>
  </dx-drop-down-button>
  <user-menu-section
    *ngIf="menuMode === 'list'"
    class="dx-toolbar-menu-action"
    [menuItems]="menuItems"
    [showAvatar]="true"
    [user]="user"
  />
</div>
