// packages/devextreme-schematics/src/add-layout/files/src/app/shared/components/user-menu-section/user-menu-section.component.ts
import { Component, NgModule, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

import { DxListModule, DxListTypes } from 'devextreme-angular/ui/list';
import { IUser } from '../../services/auth.service';

@Component({
  selector: 'user-menu-section',
  templateUrl: 'user-menu-section.component.html',
  styleUrls: ['./user-menu-section.component.scss'],
})

export class UserMenuSectionComponent {
  @Input()
  menuItems: any;

  @Input()
  showAvatar!: boolean;

  @Input()
  user!: IUser | null;

  @Output()
  onMenuItemClick = new EventEmitter();

  constructor() {}

  handleListItemClick(e: DxListTypes.ItemClickEvent) {
    e.itemData?.onClick();
    this.onMenuItemClick.emit();
  }
}

@NgModule({
  imports: [
    DxListModule,
    CommonModule,
  ],
  declarations: [UserMenuSectionComponent],
  exports: [UserMenuSectionComponent],
})
export class UserMenuSectionModule { }
<div>
  <div class="user-info">
    <div class="image-container" *ngIf="showAvatar">
      <div
        [style.backgroundImage]="'url(' + user?.avatarUrl + ')'"
        class="user-image"
      ></div>
    </div>
    <div class="user-email">{{ user?.email}}</div>
  </div>
  <dx-list
    [items]="menuItems"
    (onItemClick)="handleListItemClick($event)"
  ></dx-list>
</div>

// packages/devextreme-cli/src/templates/react/application/src/components/user-menu-section/UserMenuSection.tsx
import React, { useMemo, useCallback } from 'react';
import { useAuth } from '../../contexts/auth';
import List, { ListTypes } from 'devextreme-react/list';
import { useNavigate } from "react-router-dom";

import './UserMenuSection.scss';
<%=#isTypeScript%>import type { UserMenuSectionProps } from '../../types';<%=/isTypeScript%>

type MenuItem = {
  text<%=#isTypeScript%>: string<%=/isTypeScript%>;
  icon<%=#isTypeScript%>: string<%=/isTypeScript%>;
  onClick: () => void;
};

export const UserMenuSection = ({ showAvatar, className, onMenuItemClick }<%=#isTypeScript%>: UserMenuSectionProps<%=/isTypeScript%>) => {
  const { user, signOut } = useAuth();
  const navigate = useNavigate();

  const navigateToProfile = useCallback(() => {
    navigate("/profile");
  }, [navigate]);

  const menuItems = useMemo(
    () => [
      {
        text: "Profile",
        icon: "user",
        onClick: navigateToProfile
      },
      {
        text: 'Logout',
        icon: 'runner',
        onClick: signOut,
      },
    ],
    [signOut, navigateToProfile]
  );

  const onItemClick = useCallback(({ itemData }<%=#isTypeScript%>: ListTypes.ItemClickEvent<MenuItem><%=/isTypeScript%>) => {
    itemData<%=#isTypeScript%>?<%=/isTypeScript%>.onClick();
    onMenuItemClick<%=#isTypeScript%>?<%=/isTypeScript%>.();
  }, [onMenuItemClick]);

  return (
    <div className={className}>
      <div className='user-info'>
        { showAvatar && (
          <div className='image-container'>
            <div
              style={{
                backgroundImage: `url(${user<%=#isTypeScript%>?<%=/isTypeScript%>.avatarUrl})`,
              }}
              className='user-image'
            />
          </div>
        )}
        <div className='user-email'>{user<%=#isTypeScript%>?<%=/isTypeScript%>.email}</div>
      </div>
      <List onItemClick={onItemClick} items={menuItems} />
    </div>
  );
};
